// Generated by gencpp from file automodelcar/Intersection.msg
// DO NOT EDIT!


#ifndef AUTOMODELCAR_MESSAGE_INTERSECTION_H
#define AUTOMODELCAR_MESSAGE_INTERSECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace automodelcar
{
template <class ContainerAllocator>
struct Intersection_
{
  typedef Intersection_<ContainerAllocator> Type;

  Intersection_()
    : header()
    , distance(0)
    , angle(0.0)  {
    }
  Intersection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::automodelcar::Intersection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automodelcar::Intersection_<ContainerAllocator> const> ConstPtr;

}; // struct Intersection_

typedef ::automodelcar::Intersection_<std::allocator<void> > Intersection;

typedef boost::shared_ptr< ::automodelcar::Intersection > IntersectionPtr;
typedef boost::shared_ptr< ::automodelcar::Intersection const> IntersectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automodelcar::Intersection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automodelcar::Intersection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automodelcar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'automodelcar': ['/home/rodrigo/catkin_ws_automodelcar/src/automodelcar/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automodelcar::Intersection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automodelcar::Intersection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automodelcar::Intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automodelcar::Intersection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automodelcar::Intersection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automodelcar::Intersection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automodelcar::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8684906e20e1765a2ab9c77ed3f64e29";
  }

  static const char* value(const ::automodelcar::Intersection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8684906e20e1765aULL;
  static const uint64_t static_value2 = 0x2ab9c77ed3f64e29ULL;
};

template<class ContainerAllocator>
struct DataType< ::automodelcar::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automodelcar/Intersection";
  }

  static const char* value(const ::automodelcar::Intersection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automodelcar::Intersection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 distance\n"
"float32 angle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::automodelcar::Intersection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automodelcar::Intersection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Intersection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automodelcar::Intersection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automodelcar::Intersection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<int8_t>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMODELCAR_MESSAGE_INTERSECTION_H
