// Generated by gencpp from file automodelcar/Obstacles.msg
// DO NOT EDIT!


#ifndef AUTOMODELCAR_MESSAGE_OBSTACLES_H
#define AUTOMODELCAR_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace automodelcar
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : header()
    , detected_obstacles(0)
    , obstacle_vertices()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected_obstacles(0)
    , obstacle_vertices(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _detected_obstacles_type;
  _detected_obstacles_type detected_obstacles;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obstacle_vertices_type;
  _obstacle_vertices_type obstacle_vertices;





  typedef boost::shared_ptr< ::automodelcar::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automodelcar::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::automodelcar::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::automodelcar::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::automodelcar::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automodelcar::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automodelcar::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automodelcar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'automodelcar': ['/home/rodrigo/catkin_ws_automodelcar/src/automodelcar/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automodelcar::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automodelcar::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automodelcar::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automodelcar::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automodelcar::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automodelcar::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automodelcar::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8ba9cc95104a59374561b25f84c7880";
  }

  static const char* value(const ::automodelcar::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8ba9cc95104a593ULL;
  static const uint64_t static_value2 = 0x74561b25f84c7880ULL;
};

template<class ContainerAllocator>
struct DataType< ::automodelcar::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automodelcar/Obstacles";
  }

  static const char* value(const ::automodelcar::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automodelcar::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 detected_obstacles\n"
"geometry_msgs/Point[] obstacle_vertices\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::automodelcar::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automodelcar::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected_obstacles);
      stream.next(m.obstacle_vertices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automodelcar::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automodelcar::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected_obstacles: ";
    Printer<int8_t>::stream(s, indent + "  ", v.detected_obstacles);
    s << indent << "obstacle_vertices[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_vertices.size(); ++i)
    {
      s << indent << "  obstacle_vertices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_vertices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMODELCAR_MESSAGE_OBSTACLES_H
